name: CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v2

    # Publishing
    
    - name: dotnet publish
      run: |
        cd src/ApiReviewDotNet 
        dotnet publish -c Release -o '../../artifacts/ApiReviewDotNet'
        cd ../..

    # Deploy to Azure

    - name: webapps-deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: apireviews
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
        package: './artifacts/ApiReviewDotNet'
