name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v4

    - name: Get .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.*'

    - name: dotnet build
      run: |
        cd src/ApiReviewDotNet
        dotnet build -c Release
